// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtnvmdjnmsexlzjnwtlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0bnZtZGpubXNleGx6am53dGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjA2OTgsImV4cCI6MjA2Nzc5NjY5OH0.ZoKq53C9tZ2ohi18z0xE99IhvyMq0Rjgl8zjU1xD7GY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});